### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by SandeepDev1** [CheshireCaat/selenium-with-fingerprints#15]
```
node:internal/buffer:959
    super(bufferOrLength, byteOffset, length);
    ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:959:5)
    at createUnsafeBuffer (node:internal/buffer:1062:12)
    at allocate (node:buffer:409:10)
    at Function.allocUnsafe (node:buffer:374:10)
    at tryCreateBuffer (node:fs:421:21)
    at Object.readFileSync (node:fs:464:14)
    at EngineService.start (C:\Users\Administrator\Pictures\SeleniumTest\selenium-with-fingerprints-master\node_modules\bas-remote-node\src\services\engine.js:33:49)
    at BasRemoteClient.start (C:\Users\Administrator\Pictures\SeleniumTest\selenium-with-fingerprints-master\node_modules\bas-remote-node\src\index.js:143:24)
```

i get this error when i run the stealth.js from example

    

```require('chromedriver');
require('dotenv').config();

// Replace this import with `require('..')` if you are running the example from the repository:
const { plugin } = require('./selenium-with-fingerprints-master');
const { writeFile } = require('fs/promises');

const key = process.env.FINGERPRINT_KEY ?? '';

(async () => {
  const fingerprint = await plugin.fetch(key, { tags: ['Microsoft Windows', 'Chrome'] });
  const driver = await plugin.useFingerprint(fingerprint).launch();

  await driver.get('https://bot.sannysoft.com/');
  await new Promise((fn) => setTimeout(fn, 5000));

  await writeFile(`${__dirname}/stealth.png`, await driver.takeScreenshot(), 'base64');
  await driver.quit();
})();
```

**Comment by CheshireCaat** [comment]
Please try the latest version - the problem should be resolved.
