### ISSUE TITLE
Saving and using fingerprint with error

### ISSUE THREAD

**Issue by vpolonic** [CheshireCaat/selenium-with-fingerprints#18]
```
const { plugin } = require('puppeteer-with-fingerprints');
const { join } = require('path'); 
const fsPromises = require('fs').promises; 
const fs = require('fs');

const key = '###';
const proxyUrl = '#####';

const profile = "profile_irina";
const directoryPath = join(__dirname, profile);
const fingerprintPath = join(directoryPath, 'fingerprint.json');

async function ensureDirectoryExists(directoryPath) {
  try {
    await fsPromises.mkdir(directoryPath, { recursive: true });
    console.log(`Directory ${directoryPath} has been ensured.`);
  } catch (error) {
    console.error(`An error occurred while ensuring the directory ${directoryPath}:`, error);
    throw error;
  }
}

(async () => {
  await ensureDirectoryExists(directoryPath);
  console.log('Directory created');
  
  let fingerprint;
  if (fs.existsSync(fingerprintPath)) {
    const data = fs.readFileSync(fingerprintPath, 'utf8');
    fingerprint = JSON.parse(data);
    console.log('Fingerprint loaded from existing file.');
  } else {
    console.log('Fingerprint file does not exist. Generating a new one.');
    fingerprint = await plugin.fetch(key, {
      tags: ['Android', 'Chrome'],
      'screen.availTop': 0,
      'screen.availLeft': 0,
    });
    await fsPromises.writeFile(fingerprintPath, JSON.stringify(fingerprint, null, 2), 'utf-8');
  }
  
  plugin.useFingerprint(fingerprint);    

  plugin.useProxy(proxyUrl, {
    detectExternalIP: true,
    changeGeolocation: true,
    changeBrowserLanguage: true,
    changeTimezone: true,
    changeWebRTC: true,
  });

  console.log('Loaded fingerprint and proxy');

  const browser = await plugin.launch({
    headless: false,
    devtools: false,
    args: [`--user-data-dir=${directoryPath}`],
  });

  console.log('Browser launched');

  const page = await browser.newPage();
  await page.goto('https://google.com/', { waitUntil: 'networkidle2' });

  await page.waitForTimeout(3000);

 await browser.close();
})();
```
Returns the error:
```
Fingerprint loaded from existing file.
C:\Users\AD\Bot\node_modules\browser-with-fingerprints\src\plugin\utils.js:42
    throw new Error(`Invalid arguments for ${type} configuration.`);
          ^

Error: Invalid arguments for fingerprint configuration.
    at exports.validateConfig (C:\Users\AD\Bot\node_modules\browser-with-fingerprints\src\plugin\utils.js:42:11)
    at PuppeteerFingerprintPlugin.useFingerprint (C:\Users\AD\Bot\node_modules\browser-with-fingerprints\src\plugin\index.js:20:5)
    at C:\Users\AD\Bot\pr_irina.js:43:10
```
It is an error from the puppeteer-with-fingerprints or the way the fingerprint is saved?!

**Comment by CheshireCaat** [comment]
@vpolonic the **useFingerprint** method accepts the fingerprint as a string, you don't need to use **JSON.parse**, i.e you cannot pass an object to this method, only a string.
